<!---------------------------------------------------------------------->
<!----------------------  ADMIN INDEX  -------------------------------->
<!--------------------------------------------------------------------->
<script> var role = 'admin'; </script>
<script src="/js/guestbook/actions.js" type="text/javascript"></script>
<script src="/js/guestbook/ajax.js" type="text/javascript"></script>
<script src="/js/guestbook/main-functions.js" type="text/javascript"></script>
<script src="/js/guestbook/main.js" type="text/javascript"></script>


<h1>
    Welcome, Administrator!
    <a href="<?php echo $this->url('guestbook', array('controller'=>'auth', 'action'=>'logout')); ?>" 
       class="btn btn-default" style="float: right;">Quit</a>
</h1>
<hr/>
<!---------------------------------------------------------------------->
<!--------------------  Modal Edit Message  --------------------------->
<!--------------------------------------------------------------------->
<div class="row">
    <div class="col-md-2">
        <button class="btn btn-primary" data-toggle="modal" data-target="#editMessageModal">
                Create new Message
        </button>
    </div>
</div>
<hr/>
<div class="modal fade" id="editMessageModal" tabindex="-1" role="dialog" aria-labelledby="loginAdminModalLabel" aria-hidden="true">
  <?php
    include (__DIR__.'/../../layout/modal_edit_message.phtml');
  ?>
</div>