<!---------------------------------------------------------------------->
<!----------------------  ADMIN INDEX  -------------------------------->
<!--------------------------------------------------------------------->
<script> var role = 'admin'; </script>
<script src="/js/guestbook/actions.js" type="text/javascript"></script>
<script src="/js/guestbook/ajax.js" type="text/javascript"></script>
<script src="/js/guestbook/main-functions.js" type="text/javascript"></script>
<script src="/js/guestbook/main.js" type="text/javascript"></script>
<script src="/js/guestbook/jquery.simplePagination.js" type="text/javascript"></script>


<h1>
    Welcome, Administrator!
    <a href="<?php echo $this->url('guestbook', array('controller'=>'auth', 'action'=>'logout')); ?>" 
       class="btn btn-default" style="float: right;">Quit</a>
</h1>
<hr/>

<!---------------------------------------------------------------------->
<!--------------------  Test DIV  --------------------------->
<!--------------------------------------------------------------------->
<div id="test_div"></div>

<!---------------------------------------------------------------------->
<!--------------------  Button Create Message  --------------------------->
<!--------------------------------------------------------------------->
<div class="row">
    <div class="col-md-2">
        <button class="btn btn-primary" data-toggle="modal" data-target="#editMessageModal">
                Create new Message
        </button>
    </div>
    
<!---------------------------------------------------------------------->
<!--------------------  Form Sort Message  --------------------------->
<!--------------------------------------------------------------------->
    <div class="col-md-6">
         <?php
            include (__DIR__.'/../../layout/sort_message_form.phtml');
          ?>
    </div>
</div>
<hr/>
<!---------------------------------------------------------------------->
<!--------------------  Modal Edit Message  --------------------------->
<!--------------------------------------------------------------------->
<div class="modal fade" id="editMessageModal" tabindex="-1" role="dialog" aria-labelledby="loginAdminModalLabel" aria-hidden="true">
  <?php
    include (__DIR__.'/../../layout/modal_edit_message.phtml');
  ?>
</div>

<!---------------------------------------------------------------------->
<!------------------------  Messages Table  ------------------------------>
<!--------------------------------------------------------------------->

<div class="simplePaginator"></div>

<table style="display: none;">
    <tr class="msg_row_pattern">
        <td class="number"></td>
        <td class="user_name"></td>
        <td class="email"></td>
        <td class="short_text"></td>
        <td class="action_panel">
            <a href="#" class="btn_show_msg" data-id="" data-toggle="modal" data-target="#showMessageModal">
                Show
            </a>
            |
            <a href="#" class="btn_edit_msg" data-id="" data-toggle="modal" data-target="#editMessageModal">
                Edit
            </a>
            |
            <a href="#" class="btn_del_msg" data-id="">
                Delete
            </a>
        </td>
    </tr>
</table>

<table class="table">
    <thead>
        <tr>
            <th>№</th>
            <th>User Name</th>
            <th>User E-mail</th>
            <th>Message</th>
            <th></th>
        </tr>
    </thead>
    <tbody class="message_list">
        
    </tbody>
</table>

<div class="simplePaginator"></div>

<!---------------------------------------------------------------------->
<!--------------------  Modal Show Message  --------------------------->
<!--------------------------------------------------------------------->

<div class="modal fade" id="showMessageModal" tabindex="-1" role="dialog" aria-labelledby="loginAdminModalLabel" aria-hidden="true">
  <?php
    include (__DIR__.'/../../layout/modal_show_message_admin.phtml');
  ?>
</div>

<?php
    include (__DIR__.'/../../layout/messenger_panel.phtml');
?>