<!---------------------------------------------------------------------->
<!----------------------  GUEST INDEX  -------------------------------->
<!--------------------------------------------------------------------->
<script> var role = 'index'; </script>
<script src="/js/guestbook/actions.js" type="text/javascript"></script>
<script src="/js/guestbook/ajax.js" type="text/javascript"></script>
<script src="/js/guestbook/main-functions.js" type="text/javascript"></script>
<script src="/js/guestbook/main.js" type="text/javascript"></script>
<!---------------------------------------------------------------------->
<!-----------  Modal Singin as Administrator  --------------------------->
<!--------------------------------------------------------------------->
<div class="row">
    <div class="col-md-2">
        <button class="btn btn-primary" data-toggle="modal" data-target="#loginAdminModal">
                Singin as Administrator
        </button>
    </div>
    <div class="col-md-6">
        <?php include (__DIR__.'/../../layout/messenger.php'); ?>
    </div>
</div>
<hr/>
<div class="modal fade" id="loginAdminModal" tabindex="-1" role="dialog" aria-labelledby="loginAdminModalLabel" aria-hidden="true">
  <?php
    include (__DIR__.'/../../layout/modal_singin.phtml');
  ?>
</div>

<!---------------------------------------------------------------------->
<!--------------------  Modal Edit Message  --------------------------->
<!--------------------------------------------------------------------->
<div class="row">
    <div class="col-md-2">
        <button class="btn btn-primary" data-toggle="modal" data-target="#editMessageModal">
                Create new Message
        </button>
    </div>
</div>
<hr/>
<div class="modal fade" id="editMessageModal" tabindex="-1" role="dialog" aria-labelledby="loginAdminModalLabel" aria-hidden="true">
  <?php
    include (__DIR__.'/../../layout/modal_edit_message.phtml');
  ?>
</div>