<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="singinModalLabel">Singin as Administrator</h4>
        </div>
        <div class="modal-body">
            <?php
            $log_form = $this->login_form;
            $log_form->prepare();
            $log_form->setAttribute('action', $this->url('guestbook', array('controller' => 'auth', 'action' => 'login')));
            echo $this->form()->openTag($log_form);
            ?>
            <div class="row">
                <div class="col-md-offset-1 col-md-10">
                    <div class="form-group">
                        <?php
                        echo $this->formLabel($log_form->get('adm_pwd'));
                        echo $this->formElement($log_form->get('adm_pwd'));
                        ?>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        <div class="modal-footer">
            <?php
            echo $this->formElement($log_form->get('submit'));
            ?>
        </div>
    </div>
</div>