<?php
    $col = 3;
?>
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="editModalLabel">Message</h4>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>User Name:</dt>
                <dd class="user_name"></dd><br/>
                <dt>E-mail:</dt>
                <dd class="email"></dd><br/>
                <dt>Homepage:</dt>
                <dd class="homepage"></dd><br/>
                <dt>Message:</dt>
                <dd class="text"></dd><br/>
                <dt>User IP:</dt>
                <dd class="user_ip"></dd><br/>
                <dt>User Agent:</dt>
                <dd class="user_agent"></dd><br/>
            </dl>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>