<form id="sort_message_form" class="form-inline" method="POST">
    <div class="form-group">
        <label for="#sort_by_user_name_select">Sort by User Name</label>
        <select id="sort_by_user_name_select" name="sort_by_user_name" class="form-control">
            <option value="_none_" selected>none</option>
            <option value="_ASC_" >ascending</option>
            <option value="_DESC_" >descending</option>
        </select>
    </div>
    <div class="form-group">
        <label for="#sort_by_email_select">Sort by E-mail</label>
        <select id="sort_by_email_select" name="sort_by_email" class="form-control">
            <option value="_none_" selected>none</option>
            <option value="_ASC_" >ascending</option>
            <option value="_DESC_" >descending</option>
        </select>
    </div>
</form>