<form id="sort_message_form" method="POST">
    <label for="#sort_by_user_name_select">Sort by user name</label>
    <select id="sort_by_user_name_select" name="sort_by_user_name">
        <option value="_none_" selected>none</option>
        <option value="_ASC_" >ascending</option>
        <option value="_DESC_" >descending</option>
    </select>

    <label for="#sort_by_email_select">Sort by e-mail</label>
    <select id="sort_by_email_select" name="sort_by_email">
        <option value="_none_" selected>none</option>
        <option value="_ASC_" >ascending</option>
        <option value="_DESC_" >descending</option>
    </select>
</form>